version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Skipping tests since pytest is not used...

  build:
    commands:
      - echo Building the application...
      # Add any build-related commands here

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
